### ISSUE TITLE
Acuity Work - Standard Armpads

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/sku#5]
The standard armpads are coming up gray instead of black.  Is this something that needs to go back to FarmCP?
http://skuserver.azurewebsites.net/page/awmwtmfc.pr6.2.t.pns006s/1000/all

![acuitywork_armpads](https://cloud.githubusercontent.com/assets/13138473/10674955/403e559a-78c3-11e5-9a31-82f5d0eb7b1c.JPG)

**Comment by tucaz** [comment]
@WilliamsHeidi the default armpad for Acuity is black polymer. However, for the white chassi (like the sku you used) the armpads should be titanium. Only for this model.

If you take graphite chassi, for example, then you get the black armpad. This is by design.

http://polymer-tucaz1.c9.io/page/awmgtmfc.pr6.2.t.pns006s/1000/all

**Comment by WilliamsHeidi** [comment]
Thank you!  That makes complete sense.
